<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'amazon_config_orderimport__field__orderimport.shippingmethod__label'} = 'Mode d\'expédition de la commande';
MLI18n::gi()->{'amazon_config_orderimport__field__orderimport.shippingmethod__help'} = '<p>Amazon ne transmet pas d\'information sur le mode d\'expédition à l\'importation de la commande.</p>
<p>Vous pouvez choisir ici les modes d\'expédition disponibles sur votre boutique. Vous pouvez aussi définir vous-même, les valeurs proposées dans la liste de choix. Pour cela, rendez-vous dans le tableau d\'administration de PrestaShop, puis, sous "Expédition" > "Service d\'expédition".</p>
<p>Ce réglage est important pour l\'impression des bons de livraison et factures, ainsi que pour le traitement ultérieur de la commande en boutique et pour la gestion du stock.</p>';
MLI18n::gi()->{'amazon_config_orderimport__field__orderimport.shippingmethod__hint'} = '';
MLI18n::gi()->{'amazon_config_orderimport__field__orderimport.fbashippingmethod__label'} = 'Mode d\'expédition de la commande (FBA)';
MLI18n::gi()->{'amazon_config_orderimport__field__orderimport.fbashippingmethod__help'} = '<p>Amazon ne transmet pas d\'informations sur le mode d\'expédition avec l\'importation des commandes.</p>
<p>Choisissez ici les modes d\'expédition disponibles, pour votre boutique. Le contenus de la liste de choix est défini par vous-même. Pour cela, rendez-vous dans le menu Prestashop-Admin > expédition > du service d\'expédition.</p>
<p>Ce réglage est important pour l\'impression de bons de livraison et de factures et pour le traitement de la commande.</p>';
MLI18n::gi()->{'amazon_config_orderimport__field__orderimport.fbashippingmethod__hint'} = '';
