<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameEtsy'} = 'Etsy';
MLI18n::gi()->{'etsy_upload_explanation'} = 'The marketplace processes your data and checks for content mistakes. The article processing can last up to 24 hours.';
MLI18n::gi()->{'etsy_info_add_upload'} = 'Each item that has been posted on Etsy marketplace<br/> is being charged by Etsy ! <br/><br/> Please wait a moment...';
MLI18n::gi()->{'etsy_prepare_description_not_valid'} = 'Item description is too long. Maximum number of characters is 63000.';
MLI18n::gi()->{'etsy_prepare_images_not_valid'} = 'The picture is too big. The maximum allowed image size is 3000 x 3000 px.';
MLI18n::gi()->{'etsy_prepare_images_not_exist'} = 'There must be at least one image for the item !';
MLI18n::gi()->{'etsy_prepare_description_not_exist'} = 'Item description is too short.';
MLI18n::gi()->{'etsy_prepare_price_not_valid'} = 'Minimum item price on Etsy is 0.17£';
MLI18n::gi()->{'etsy_prepare_quantity_not_valid'} = 'The stock for a product must not be larger than 999.';

MLI18n::gi()->{'etsy_inventory_listing_status_new'} = 'Product will be created';
MLI18n::gi()->{'etsy_inventory_listing_status_update'} = 'Product will be updated';
MLI18n::gi()->{'etsy_inventory_listing_status_active'} = 'Active';