-- REQUEST --
CREATE TABLE IF NOT EXISTS {PREFIXE}vex_urbaner_holidays (
	id INT(100) NOT NULL AUTO_INCREMENT,
	date DATE NULL DEFAULT NULL,
	concep VARCHAR(10) NULL DEFAULT NULL,
	PRIMARY KEY (id)
)DEFAULT CHARSET=utf8;
-- REQUEST --
CREATE TABLE IF NOT EXISTS {PREFIXE}vex_urbaner_horarys (
	id INT(10) NULL DEFAULT NULL,
	day VARCHAR(20) NULL DEFAULT NULL,
	start TIME NULL DEFAULT NULL,
	end TIME NULL DEFAULT NULL,
	status INT(10) NULL DEFAULT NULL
)DEFAULT CHARSET=utf8;
-- REQUEST --
CREATE TABLE IF NOT EXISTS {PREFIXE}vex_urbaner_orders (
	id_vex_urbaner INT(200) NOT NULL,
	id_wsl INT(200) NOT NULL,
	type INT(200) NOT NULL,
	id_traking INT(200) NULL DEFAULT NULL,
	referency VARCHAR(200) NOT NULL,
	response VARCHAR(200) NULL DEFAULT NULL,
	date VARCHAR(200) NULL DEFAULT NULL,
	price FLOAT NULL DEFAULT NULL,
	status VARCHAR(200) NULL DEFAULT NULL,
	address VARCHAR(100) NULL DEFAULT NULL,
	lanLot VARCHAR(500) NULL DEFAULT NULL,
	urlTracking VARCHAR(500) NULL DEFAULT NULL,
	vehicle_id VARCHAR(100) NULL DEFAULT NULL,
	date_creation DATETIME NULL DEFAULT NULL
)DEFAULT CHARSET=utf8;
-- REQUEST --
CREATE TABLE IF NOT EXISTS {PREFIXE}vex_urbaner_stores (
	id INT(20) NULL DEFAULT NULL,
	id_ws INT(20) NULL DEFAULT NULL,
	name_ws VARCHAR(200) NULL DEFAULT NULL,
	country VARCHAR(50) NULL DEFAULT NULL,
	zip_code VARCHAR(50) NULL DEFAULT NULL,
	persone VARCHAR(100) NULL DEFAULT NULL,
	address VARCHAR(200) NULL DEFAULT NULL,
	mail VARCHAR(200) NULL DEFAULT NULL,
	address_2 VARCHAR(200) NULL DEFAULT NULL,
	city VARCHAR(20) NULL DEFAULT NULL,
	time VARCHAR(20) NULL DEFAULT NULL,
	phone VARCHAR(20) NULL DEFAULT NULL,
	lat VARCHAR(1000) NULL DEFAULT NULL,
	lnt VARCHAR(1000) NULL DEFAULT NULL
)DEFAULT CHARSET=utf8;