<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'form_type_optional_select__true'} = 'Utiliser';
MLI18n::gi()->{'form_type_optional_select__false'} = 'Ne pas utiliser';
MLI18n::gi()->{'form_type_matching_select_optional'} = 'Veuillez sélectionner';
MLI18n::gi()->{'form_type_matching_multi_select'} = 'Multiselect';
MLI18n::gi()->{'form_type_matching_select_all'} = 'Tout';
MLI18n::gi()->{'form_type_matching_select_reset'} = 'Supprimer le matching';
MLI18n::gi()->{'form_type_matching_select_manual'} = 'Classer manuellement ';
MLI18n::gi()->{'form_type_matching_select_auto'} = 'Matching automatique';
MLI18n::gi()->{'form_type_duplicate_radiogroup'} = 'Standard';
MLI18n::gi()->{'form_type_matching_optional'} = 'Ne pas transmettre';
MLI18n::gi()->{'form_text_addon_error'} = 'L\'extension {#Sku#} n\'a pas pu être réserver. <br /> <br />Erreur : {#Error#}';
MLI18n::gi()->{'form_text_addon_success'} = 'L\'extension {#Sku#} a été réservée avec succès. Vous recevrez sous peu une confirmation par courriel.';
MLI18n::gi()->{'form_action_default_legend'} = 'Actions';
MLI18n::gi()->{'form_action_prepare'} = 'Enregistrer';
MLI18n::gi()->{'form_action_unprepare'} = 'Annuler';
MLI18n::gi()->{'form_action_save'} = 'Enregistrer';
MLI18n::gi()->{'form_action_wizard_save'} = 'Continuez vers "%s"';
MLI18n::gi()->{'form_action_finish_wizard_save'} = 'Terminez';
MLI18n::gi()->{'form_action_expert'} = 'Réglages expert';
MLI18n::gi()->{'form_action_reset'} = 'Retour';
MLI18n::gi()->{'form_text_choose'} = 'Sélectionnez';
