<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameConfiguration'} = 'Configuration générale';
MLI18n::gi()->{'sChangeKeyAlert'} = '<div id="switchSKU" class="dialog2" title="{#i18n:ML_TEXT_CONFIRM_SKU_CHANGE_TITLE#}">{#i18n:ML_TEXT_CONFIRM_SKU_CHANGE_TEXT#}</div>';
MLI18n::gi()->{'sWarningGlobalConfigurationIsNotConfigured'} = 'Pour poursuivre, veuillez d’abord procéder à la configuration générale et la sauvegarder.';