<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameEbay'} = 'eBay';
MLI18n::gi()->{'sEbayNoInternationalShipping'} = 'Ne pas expédier à l\'étranger';
MLI18n::gi()->{'sEbayProductIdentifierSyncButton'} = 'Synchronisation des codes EAN et MPN vers eBay';
MLI18n::gi()->{'sEbaySyncButtonDisableIfno'} = 'Cette fonction n\'est pas disponible.';
MLI18n::gi()->{'sEbayDefaultValueText'} = 'Valeur par défaut';
MLI18n::gi()->{'ML_EBAY_N_PENDING_UPDATES_TITLE_ITEMS'} = 'Synchronisation des prix et des stocks:';
MLI18n::gi()->{'ML_EBAY_N_PENDING_UPDATES_TITLE_PRODUCTDETAILUPDATES'} = 'Attributs requis par eBay :';
MLI18n::gi()->{'ML_EBAY_PLUS_ORDER'} = 'Ceci est une commande <span style="color:red;">eBay Plus</span>.';
MLI18n::gi()->{'ML_TEXT_WARNING'} = 'Avertissement';
MLI18n::gi()->{'ML_EBAY_PLUS_ORDER_WRONG_SHIPPING'} = 'Le mode de livraison choisit n\'est pas compatible avec eBay plus.';
MLI18n::gi()->{'eBaySalesRecordNumber'} = 'Numéro de protocole de vente';
