<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Amazon_Label_sAutoMatchSuccess'} = 'Products with an EAN-field are prepared.';
MLI18n::gi()->{'Amazon_BUTTON_LABEL_DELETE_COMPLETE_LOG'} = 'Delete complete log';
MLI18n::gi()->{'amazon_prepare_apply'} = 'Create New Products';
MLI18n::gi()->{'ML_AMAZON_ERROR_TEMPLATENAME_EMPTY'} = 'You activated the „use seller shipping groups“ function but didn’t define seller groups. Please define at least one seller group (as seen under item preparation > seller shipping groups)';
