<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'configform_check_entries_error'} = 'Please the red-marked entries.';
MLI18n::gi()->{'configform_quantity_value_error'} = 'The quantity must be a decimal number';
MLI18n::gi()->{'configform_price_factor_error'} = 'Markup and Markdown field must be numeric.';
MLI18n::gi()->{'configform_price_signal_error'} = 'The position after deimal point must be a decimal number.';
MLI18n::gi()->{'configform_ust_error'} = 'The VAT must be numeric.';
