<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'configform_quantity_values__stock__title'} = 'Transfer shop inventory';
MLI18n::gi()->{'configform_quantity_values__stock__textoption'} = '';
MLI18n::gi()->{'configform_quantity_values__stocksub__title'} = 'Transfer shop inventory minus value from the right field';
MLI18n::gi()->{'configform_quantity_values__stocksub__textoption'} = '1';
MLI18n::gi()->{'configform_quantity_values__lump__title'} = 'Flat amount (from the right field)';
MLI18n::gi()->{'configform_quantity_values__lump__textoption'} = '1';
MLI18n::gi()->{'configform_price_addkind_values__percent'} = 'Markup/Markdown of x% of Shop price';
MLI18n::gi()->{'configform_price_addkind_values__addition'} = 'Markup/Markdown Shop price by x';
MLI18n::gi()->{'configform_sync_value_auto'} = 'Automatic synchronization via CronJob (recommended)';
MLI18n::gi()->{'configform_sync_value_fast'} = 'Faster automatic synchronization (CronJob to 15 minutes)';
MLI18n::gi()->{'configform_sync_value_no'} = 'No synchronization';
MLI18n::gi()->{'configform_sync_values__auto'} = '{#i18n:configform_sync_value_auto#}';
MLI18n::gi()->{'configform_sync_values__no'} = '{#i18n:configform_sync_value_no#}';
MLI18n::gi()->{'configform_fast_sync_values__auto'} = '{#i18n:configform_sync_value_auto#}';
MLI18n::gi()->{'configform_fast_sync_values__no'} = '{#i18n:configform_sync_value_no#}';
MLI18n::gi()->{'configform_stocksync_values__rel'} = 'Orders reduce Shop inventory (recommended)';
MLI18n::gi()->{'configform_stocksync_values__no'} = '{#i18n:configform_sync_value_no#}';
MLI18n::gi()->{'configform_price_field_priceoptions_help'} = 'This function allows you to define other prices for the Marketplace. These prices will be used in item upload as well as in the price synchronization.<ul>
<li>Use a customer group, or define an own customer group where you place the prices for the marketplace.</li>
<li>If an item has no price defined for the price group chosen, the default price will be used.</li></ul>
This way, you can change the prices for only a few items without changing the calculation rules for everything.<br />
The other configuration settings (Markup/Markdown and Decimal amount) apply here as well.';
MLI18n::gi()->{'configform_emailtemplate_legend'} = 'E-Mail to Buyer';
MLI18n::gi()->{'configform_emailtemplate_field_send_label'} = 'Send E-Mail?';
MLI18n::gi()->{'configform_emailtemplate_field_send_help'} = 'Should an email be sent from your Shop to customers?';
MLI18n::gi()->{'generic_prepareform_day'} = 'day';