<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Amazon_Label_sAutoMatchSuccess'} = 'Les articles avec les numéros EAN sont préparés.';
MLI18n::gi()->{'Amazon_BUTTON_LABEL_DELETE_COMPLETE_LOG'} = 'Effacer toute la cession (Log)';
MLI18n::gi()->{'amazon_prepare_apply'} = 'Nouveaux articles';
MLI18n::gi()->{'ML_AMAZON_ERROR_TEMPLATENAME_EMPTY'} = 'Vous avez activé la fonction "Utiliser les profils de paramètres d\'expédition par régions d\'expédition" sans spécifier un profil d\'expédition. Veuillez saisir au moins un profil de livraison.';
