<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'priceminister_prepare_form__legend__details'} = 'priceminister_prepare_form__legend__details';
MLI18n::gi()->{'priceminister_prepare_form__legend__categories'} = 'priceminister_prepare_form__legend__categories';
MLI18n::gi()->{'priceminister_prepare_form__legend__variationmatching__0'} = '{#i18n:attributes_matching_required_attributes#}';
MLI18n::gi()->{'priceminister_prepare_form__legend__variationmatching__1'} = '{#i18n:attributes_matching_title#}';
MLI18n::gi()->{'priceminister_prepare_form__legend__configmatching'} = 'priceminister_prepare_form__legend__configmatching';
MLI18n::gi()->{'priceminister_prepare_form__field__categories__label'} = 'priceminister_prepare_form__field__categories__label';
MLI18n::gi()->{'priceminister_prepare_form__field__primarycategory__label'} = 'priceminister_prepare_form__field__primarycategory__label';
MLI18n::gi()->{'priceminister_prepare_form__field__currency__label'} = 'priceminister_prepare_form__field__currency__label';
MLI18n::gi()->{'priceminister_prepare_form__field__itemcondition__label'} = 'priceminister_prepare_form__field__itemcondition__label';
MLI18n::gi()->{'priceminister_prepare_form__field__listingtype__label'} = 'priceminister_prepare_form__field__listingtype__label';
MLI18n::gi()->{'priceminister_prepare_form__field__buyingmode__label'} = 'priceminister_prepare_form__field__buyingmode__label';
MLI18n::gi()->{'priceminister_prepare_form__field__shippingmode__label'} = 'priceminister_prepare_form__field__shippingmode__label';
MLI18n::gi()->{'priceminister_prepare_form__field__webshopattribute__label'} = 'priceminister_prepare_form__field__webshopattribute__label';
MLI18n::gi()->{'priceminister_prepare_form__field__attributematching__matching__titlesrc'} = 'priceminister_prepare_form__field__attributematching__matching__titlesrc';
MLI18n::gi()->{'priceminister_prepare_form__field__attributematching__matching__titledst'} = 'priceminister_prepare_form__field__attributematching__matching__titledst';
MLI18n::gi()->{'priceminister_prepareform_max_length_part1'} = 'priceminister_prepareform_max_length_part1';
MLI18n::gi()->{'priceminister_prepareform_max_length_part2'} = 'priceminister_prepareform_max_length_part2';
MLI18n::gi()->{'priceminister_prepareform_reqired_fieds'} = 'priceminister_prepareform_reqired_fieds';
