<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameHitmeister'} = 'Hitmeister';
MLI18n::gi()->{'hitmeister_label_title'} = 'Titre sur Hitmeister';
MLI18n::gi()->{'hitmeister_category'} = 'Catégorie Hitmeister';
MLI18n::gi()->{'hitmeister_label_item_id'} = 'Identifiant de l\'article';
MLI18n::gi()->{'hitmeister_search_by_title'} = 'Rechercher par titre';
MLI18n::gi()->{'hitmeister_search_by_ean'} = 'Rechercher par code EAN';
MLI18n::gi()->{'hitmeister_label_not_matched'} = 'ne pas classer (matching)';
MLI18n::gi()->{'hitmeister_upload_explanation'} = 'Les articles diffusés sur Hitmeister, dont les codes EAN sont connus, sont traités dans l\'espace d\'une heure.
<br /><br />
Les articles dont les codes EAN ne sont pas encore listés sur Hitmeister, sont transmis chaque nuit à partir de 00:00 h.
<br /><br />
Pour l\'assurance de qualité des offres, les données sont traitées manuellement par Hitmeister. Le traitement peut durer 2 à 4 jours. Vous pouvez surveiller le statut du traitement dans votre compte de vendeur sur Hitmeister.';
