<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'hitmeister_inventory_listing_quantity'} = 'Stock<br /> Boutique / Hitmeister';
MLI18n::gi()->{'hitmeister_inventory_listing_status'} = 'Statut';
MLI18n::gi()->{'hitmeister_inventory_listing_status_active'} = 'Actif';
MLI18n::gi()->{'hitmeister_inventory_listing_status_pending_new'} = 'Création d\'un nouvel article en cours';
MLI18n::gi()->{'hitmeister_inventory_listing_status_pending_update'} = 'Mise à jours en cours';
