<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'hitmeister_prepare_match_manual__legend__unit'} = 'Attributs d\'articles';
MLI18n::gi()->{'hitmeister_prepare_match_manual__legend__manualmatching'} = 'Classement (matching)';
MLI18n::gi()->{'hitmeister_prepare_match_manual__field__itemcondition__label'} = 'État de l\'article';
MLI18n::gi()->{'hitmeister_prepare_match_manual__field__shippingtime__label'} = 'Délais de livraison';
MLI18n::gi()->{'hitmeister_prepare_match_manual__field__itemcountry__label'} = 'L\'article est expédié depuis';
MLI18n::gi()->{'hitmeister_prepare_match_manual__field__comment__label'} = 'Informations sur l\'article';
MLI18n::gi()->{'form_action_prepare_and_next'} = 'Sauvegarder et continuer';
MLI18n::gi()->{'hitmeister_label_product_at_hitmeister'} = 'Article sur Hitmeister';
