<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Hitmeister_Productlist_Cell_aPreparedStatus__OK__title'} = 'Préparé avec succès';
MLI18n::gi()->{'Hitmeister_Productlist_Cell_aPreparedStatus__ERROR__title'} = 'Mal préparé';
MLI18n::gi()->{'Hitmeister_Productlist_Cell_aPreparedStatus__OPEN__title'} = 'Préparation non vérifiée';
MLI18n::gi()->{'Hitmeister_Productlist_Label_Price'} = 'Prix real.de';
MLI18n::gi()->{'Hitmeister_Productlist_Filter_aPreparedStatus__OK'} = 'Préparé avec succès';
MLI18n::gi()->{'Hitmeister_Productlist_Filter_aPreparedStatus__ERROR'} = 'Mal préparé';
MLI18n::gi()->{'Hitmeister_Productlist_Filter_aPreparedStatus__OPEN'} = 'Préparation non vérifiée\'';
MLI18n::gi()->{'Hitmeister_Productlist_Match_Manual_Title_Single'} = 'Classement individuel (matching)';
MLI18n::gi()->{'Hitmeister_Productlist_Match_Manual_Title_Multi'} = 'Classment multiple (matching)';
MLI18n::gi()->{'Hitmeister_Productlist_Match_Auto_Title'} = 'Classement automatique (matching)';
MLI18n::gi()->{'Hitmeister_Productlist_Match_Auto_Summary'} = '%d des articles ont été classés (matching) avec succès. <br/ ><br/ >
	%d des articles n\'ont pas été classés (matching) avec succès.<br />
	Entre eux %d ont générés plusieurs résultats.';
MLI18n::gi()->{'Hitmeister_Productlist_Match_Manual_Desc'} = 'Les articles de la boutique sélectionnée par Checkbox vont être préparés en arrière plan: L\'article va être classé (matching) automatiquement avec les numéros EAN des articles correspondants sur Hitmeister grâce aux numéros EAN pré-enregistrés de cet article.<br/ ><br/ > Il est donc primordial de mettre à jour régulièrement les numéros EAN de chaque produit.';
MLI18n::gi()->{'Hitmeister_Productlist_Match_Auto_Desc'} = 'Les articles de la boutique sélectionnée par Checkbox vont être préparés en arrière plan: L\'article va être classé (matching) automatiquement avec les numéros EAN des articles correspondants sur Cdisount grâce aux numéros EAN pré-enregistrés de cet article.<br/ ><br/ > Il est donc primordial de mettre à jour régulièrement les numéros EAN de chaque produit.';
MLI18n::gi()->{'Hitmeister_Productlist_Match_Auto_Confirm'} = 'Attention, le classement (matching) se fait automatiquement et exclusivement à partir de l\'ajustement des numéros EAN. Certains articles de Hitmeister vont être classés (matching) en présentant une qualité inférieure au niveau de la description et des photos. Ce qui va provoquer alors de mauvais résultats, plus mauvais qu\'avec un classement (matching) manuel.<br/ ><br/ > RedGecko décline alors toutes responsabilités en cas d\'inexactitude de l\'article proposé.';
MLI18n::gi()->{'Hitmeister_Productlist_Cell_aPreparedType__manual'} = 'Classement manuel (matching)';
MLI18n::gi()->{'Hitmeister_Productlist_Cell_aPreparedType__auto'} = 'Classement automatique (matching)';
MLI18n::gi()->{'Hitmeister_Productlist_Cell_aPreparedType__apply'} = 'Créer un nouveau produit';
