<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'ebay_prepare_apply'} = 'ebay_prepare_apply';
MLI18n::gi()->{'ml_ebay_prepare_form_category_notvalid'} = 'ml_ebay_prepare_form_category_notvalid';
MLI18n::gi()->{'ml_ebay_no_conditions_applicable_for_cat'} = 'ml_ebay_no_conditions_applicable_for_cat';
MLI18n::gi()->{'ebay_prepare_apply_form__legend__details'} = 'ebay_prepare_apply_form__legend__details';
MLI18n::gi()->{'ebay_prepare_apply_form__legend__auction'} = 'ebay_prepare_apply_form__legend__auction';
MLI18n::gi()->{'ebay_prepare_apply_form__legend__category'} = 'ebay_prepare_apply_form__legend__category';
MLI18n::gi()->{'ebay_prepare_apply_form__legend__primarycategory_attributes'} = 'ebay_prepare_apply_form__legend__primarycategory_attributes';
MLI18n::gi()->{'ebay_prepare_apply_form__legend__secondarycategory_attributes'} = 'ebay_prepare_apply_form__legend__secondarycategory_attributes';
MLI18n::gi()->{'ebay_prepare_apply_form__legend__shipping'} = 'ebay_prepare_apply_form__legend__shipping';
MLI18n::gi()->{'ebay_prepare_apply_form__field__title__label'} = 'ebay_prepare_apply_form__field__title__label';
MLI18n::gi()->{'ebay_prepare_apply_form__field__title__hint'} = 'ebay_prepare_apply_form__field__title__hint';
MLI18n::gi()->{'ebay_prepare_apply_form__field__title__optional__checkbox__labelNegativ'} = 'ebay_prepare_apply_form__field__title__optional__checkbox__labelNegativ';
MLI18n::gi()->{'ebay_prepare_apply_form__field__subtitle__label'} = 'ebay_prepare_apply_form__field__subtitle__label';
MLI18n::gi()->{'ebay_prepare_apply_form__field__subtitle__hint'} = 'ebay_prepare_apply_form__field__subtitle__hint';
MLI18n::gi()->{'ebay_prepare_apply_form__field__subtitle__optional__select__false'} = 'ebay_prepare_apply_form__field__subtitle__optional__select__false';
MLI18n::gi()->{'ebay_prepare_apply_form__field__subtitle__optional__select__true'} = 'ebay_prepare_apply_form__field__subtitle__optional__select__true';
MLI18n::gi()->{'ebay_prepare_apply_form__field__pictureurl__label'} = 'ebay_prepare_apply_form__field__pictureurl__label';
MLI18n::gi()->{'ebay_prepare_apply_form__field__pictureurl__hint'} = 'ebay_prepare_apply_form__field__pictureurl__hint';
MLI18n::gi()->{'ebay_prepare_apply_form__field__galleryurl__label'} = 'ebay_prepare_apply_form__field__galleryurl__label';
MLI18n::gi()->{'ebay_prepare_apply_form__field__galleryurl__hint'} = 'ebay_prepare_apply_form__field__galleryurl__hint';
MLI18n::gi()->{'ebay_prepare_apply_form__field__galleryurl__optional__select__false'} = 'ebay_prepare_apply_form__field__galleryurl__optional__select__false';
MLI18n::gi()->{'ebay_prepare_apply_form__field__galleryurl__optional__select__true'} = 'ebay_prepare_apply_form__field__galleryurl__optional__select__true';
MLI18n::gi()->{'ebay_prepare_apply_form__field__description__label'} = 'ebay_prepare_apply_form__field__description__label';
MLI18n::gi()->{'ebay_prepare_apply_form__field__description__hint'} = 'ebay_prepare_apply_form__field__description__hint';
MLI18n::gi()->{'ebay_prepare_apply_form__field__description__optional__checkbox__labelNegativ'} = 'ebay_prepare_apply_form__field__description__optional__checkbox__labelNegativ';
MLI18n::gi()->{'ebay_prepare_apply_form__field__pricecontainer__label'} = 'ebay_prepare_apply_form__field__pricecontainer__label';
MLI18n::gi()->{'ebay_prepare_apply_form__field__pricecontainer__hint'} = 'ebay_prepare_apply_form__field__pricecontainer__hint';
MLI18n::gi()->{'ebay_prepare_apply_form__field__buyitnowprice__optional__select__true'} = 'ebay_prepare_apply_form__field__buyitnowprice__optional__select__true';
MLI18n::gi()->{'ebay_prepare_apply_form__field__buyitnowprice__optional__select__false'} = 'ebay_prepare_apply_form__field__buyitnowprice__optional__select__false';
MLI18n::gi()->{'ebay_prepare_apply_form__field__site__label'} = 'ebay_prepare_apply_form__field__site__label';
MLI18n::gi()->{'ebay_prepare_apply_form__field__site__hint'} = 'ebay_prepare_apply_form__field__site__hint';
MLI18n::gi()->{'ebay_prepare_apply_form__field__listingtype__label'} = 'ebay_prepare_apply_form__field__listingtype__label';
MLI18n::gi()->{'ebay_prepare_apply_form__field__listingtype__hint'} = 'ebay_prepare_apply_form__field__listingtype__hint';
MLI18n::gi()->{'ebay_prepare_apply_form__field__listingduration__label'} = 'ebay_prepare_apply_form__field__listingduration__label';
MLI18n::gi()->{'ebay_prepare_apply_form__field__listingduration__hint'} = 'ebay_prepare_apply_form__field__listingduration__hint';
MLI18n::gi()->{'ebay_prepare_apply_form__field__paymentmethods__label'} = 'ebay_prepare_apply_form__field__paymentmethods__label';
MLI18n::gi()->{'ebay_prepare_apply_form__field__paymentmethods__hint'} = 'ebay_prepare_apply_form__field__paymentmethods__hint';
MLI18n::gi()->{'ebay_prepare_apply_form__field__conditionid__label'} = 'ebay_prepare_apply_form__field__conditionid__label';
MLI18n::gi()->{'ebay_prepare_apply_form__field__conditionid__hint'} = 'ebay_prepare_apply_form__field__conditionid__hint';
MLI18n::gi()->{'ebay_prepare_apply_form__field__privatelisting__label'} = 'ebay_prepare_apply_form__field__privatelisting__label';
MLI18n::gi()->{'ebay_prepare_apply_form__field__privatelisting__hint'} = 'ebay_prepare_apply_form__field__privatelisting__hint';
MLI18n::gi()->{'ebay_prepare_apply_form__field__bestofferenabled__label'} = 'ebay_prepare_apply_form__field__bestofferenabled__label';
MLI18n::gi()->{'ebay_prepare_apply_form__field__bestofferenabled__hint'} = 'ebay_prepare_apply_form__field__bestofferenabled__hint';
MLI18n::gi()->{'ebay_prepare_apply_form__field__ebayplus__label'} = 'ebay_prepare_apply_form__field__ebayplus__label';
MLI18n::gi()->{'ebay_prepare_apply_form__field__ebayplus__hint'} = 'ebay_prepare_apply_form__field__ebayplus__hint';
MLI18n::gi()->{'ebay_prepare_apply_form__field__hitcounter__label'} = 'ebay_prepare_apply_form__field__hitcounter__label';
MLI18n::gi()->{'ebay_prepare_apply_form__field__hitcounter__hint'} = '';
MLI18n::gi()->{'ebay_prepare_apply_form__field__starttime__label'} = 'ebay_prepare_apply_form__field__starttime__label';
MLI18n::gi()->{'ebay_prepare_apply_form__field__starttime__hint'} = 'ebay_prepare_apply_form__field__starttime__hint';
MLI18n::gi()->{'ebay_prepare_apply_form__field__primarycategory__label'} = 'ebay_prepare_apply_form__field__primarycategory__label';
MLI18n::gi()->{'ebay_prepare_apply_form__field__primarycategory__hint'} = 'ebay_prepare_apply_form__field__primarycategory__hint';
MLI18n::gi()->{'ebay_prepare_apply_form__field__secondarycategory__label'} = 'ebay_prepare_apply_form__field__secondarycategory__label';
MLI18n::gi()->{'ebay_prepare_apply_form__field__secondarycategory__hint'} = 'ebay_prepare_apply_form__field__secondarycategory__hint';
MLI18n::gi()->{'ebay_prepare_apply_form__field__storecategory__label'} = 'ebay_prepare_apply_form__field__storecategory__label';
MLI18n::gi()->{'ebay_prepare_apply_form__field__storecategory__hint'} = 'ebay_prepare_apply_form__field__storecategory__hint';
MLI18n::gi()->{'ebay_prepare_apply_form__field__storecategory2__label'} = 'ebay_prepare_apply_form__field__storecategory2__label';
MLI18n::gi()->{'ebay_prepare_apply_form__field__storecategory2__hint'} = 'ebay_prepare_apply_form__field__storecategory2__hint';
MLI18n::gi()->{'ebay_prepare_apply_form__field__shippinglocalcontainer__label'} = 'ebay_prepare_apply_form__field__shippinglocalcontainer__label';
MLI18n::gi()->{'ebay_prepare_apply_form__field__shippinglocalcontainer__hint'} = 'ebay_prepare_apply_form__field__shippinglocalcontainer__hint';
MLI18n::gi()->{'ebay_prepare_apply_form__field__shippinginternationalcontainer__label'} = 'ebay_prepare_apply_form__field__shippinginternationalcontainer__label';
MLI18n::gi()->{'ebay_prepare_apply_form__field__shippinginternationalcontainer__hint'} = 'ebay_prepare_apply_form__field__shippinginternationalcontainer__hint';
MLI18n::gi()->{'ebay_prepare_apply_form__field__shippinglocal__cost'} = 'ebay_prepare_apply_form__field__shippinglocal__cost';
MLI18n::gi()->{'ebay_prepare_apply_form__field__shippinglocalprofile__option'} = 'ebay_prepare_apply_form__field__shippinglocalprofile__option';
MLI18n::gi()->{'ebay_prepare_apply_form__field__shippinglocalprofile__optional__select__false'} = 'ebay_prepare_apply_form__field__shippinglocalprofile__optional__select__false';
MLI18n::gi()->{'ebay_prepare_apply_form__field__shippinglocalprofile__optional__select__true'} = 'ebay_prepare_apply_form__field__shippinglocalprofile__optional__select__true';
MLI18n::gi()->{'ebay_prepare_apply_form__field__shippinglocaldiscount__label'} = 'ebay_prepare_apply_form__field__shippinglocaldiscount__label';
MLI18n::gi()->{'ebay_prepare_apply_form__field__shippinginternationaldiscount__label'} = 'ebay_prepare_apply_form__field__shippinginternationaldiscount__label';
MLI18n::gi()->{'ebay_prepare_apply_form__field__shippinginternational__cost'} = 'ebay_prepare_apply_form__field__shippinginternational__cost';
MLI18n::gi()->{'ebay_prepare_apply_form__field__shippinginternational__optional__select__false'} = 'ebay_prepare_apply_form__field__shippinginternational__optional__select__false';
MLI18n::gi()->{'ebay_prepare_apply_form__field__shippinginternational__optional__select__true'} = 'ebay_prepare_apply_form__field__shippinginternational__optional__select__true';
MLI18n::gi()->{'ebay_prepare_apply_form__field__dispatchtimemax__label'} = 'ebay_prepare_apply_form__field__dispatchtimemax__label';
MLI18n::gi()->{'ebay_prepare_apply_form__field__dispatchtimemax__optional__checkbox__labelNegativ'} = 'ebay_prepare_apply_form__field__dispatchtimemax__optional__checkbox__labelNegativ';
MLI18n::gi()->{'ebay_prepare_apply_form__field__shippinginternationalprofile__option'} = 'ebay_prepare_apply_form__field__shippinginternationalprofile__option';
MLI18n::gi()->{'ebay_prepare_apply_form__field__shippinginternationalprofile__notavailible'} = 'ebay_prepare_apply_form__field__shippinginternationalprofile__notavailible';
MLI18n::gi()->{'ebay_prepare_apply_form__field__shippinginternationalprofile__optional__select__false'} = 'ebay_prepare_apply_form__field__shippinginternationalprofile__optional__select__false';
MLI18n::gi()->{'ebay_prepare_apply_form__field__shippinginternationalprofile__optional__select__true'} = 'ebay_prepare_apply_form__field__shippinginternationalprofile__optional__select__true';


MLI18n::gi()->{'ebay_prepare_apply_form__legend__variationmatching__0'} = '{#i18n:attributes_matching_required_attributes#}';
MLI18n::gi()->{'ebay_prepare_apply_form__legend__variationmatching__1'} = '{#i18n:attributes_matching_title#}';
MLI18n::gi()->{'ebay_prepare_apply_form__legend__variationmatchingoptional__0'} = '{#i18n:attributes_matching_optional_attributes#}';
MLI18n::gi()->{'ebay_prepare_apply_form__legend__variationmatchingoptional__1'} = '{#i18n:attributes_matching_title#}';
MLI18n::gi()->{'ebay_prepare_apply_form__legend__variationmatchingcustom__0'} = '{#i18n:attributes_matching_custom_attributes#}';
MLI18n::gi()->{'ebay_prepare_apply_form__legend__variationmatchingcustom__1'} = '{#i18n:attributes_matching_title#}';
MLI18n::gi()->{'ebay_prepare_apply_form__field__variationgroups__label'} = 'ebay_prepare_apply_form__field__variationgroups__label';
MLI18n::gi()->{'ebay_prepare_apply_form__field__variationgroups.value__label'} = 'ebay_prepare_apply_form__field__variationgroups.value__label';
MLI18n::gi()->{'ebay_prepare_apply_form__field__variationgroups.value__catinfo'} = 'ebay_prepare_apply_form__field__variationgroups.value__catinfo';
MLI18n::gi()->{'ebay_prepare_apply_form__field__webshopattribute__label'} = 'ebay_prepare_apply_form__field__webshopattribute__label';
MLI18n::gi()->{'ebay_prepare_apply_form__field__attributematching__matching__titlesrc'} = 'ebay_prepare_apply_form__field__attributematching__matching__titlesrc';
MLI18n::gi()->{'ebay_prepare_apply_form__field__attributematching__matching__titledst'} = 'ebay_prepare_apply_form__field__attributematching__matching__titledst';


MLI18n::gi()->add('ebay_prepare_variations', array(
    'legend' => array(
        'variations' => 'Kategorie von eBay ausw&auml;hlen',
        'attributes' => 'Attributsnamen von eBay ausw&auml;hlen',
        'variationmatching' => array('{#i18n:attributes_matching_required_attributes#}', '{#i18n:attributes_matching_title#}'),
        'variationmatchingoptional' => array('{#i18n:attributes_matching_optional_attributes#}', '{#i18n:attributes_matching_title#}'),
        'variationmatchingcustom' => array('{#i18n:attributes_matching_custom_attributes#}', '{#i18n:attributes_matching_title#}'),
        'action' => '{#i18n:form_action_default_legend#}',
    ),
    'field' => array(
        'variationgroups' => array(
            'label' => 'eBay Kategorie',
        ),
        'variationgroups.value' => array(
            'label' => '1. Marktplatz-Kategorie:',
        ),
        'deleteaction' => array(
            'label' => '{#i18n:ML_BUTTON_LABEL_DELETE#}',
        ),
        'groupschanged' => array(
            'label' => '',
        ),
        'attributename' => array(
            'label' => 'Attributsnamen',
        ),
        'attributenameajax' => array(
            'label' => '',
        ),
        'customidentifier' => array(
            'label' => 'Bezeichner',
        ),
        'webshopattribute' => array(
            'label' => 'Web-Shop Attribut',
        ),
        'saveaction' => array(
            'label' => 'SPEICHERN UND SCHLIESSEN',
        ),
        'resetaction' => array(
            'label' => '{#i18n:ebay_varmatch_reset_matching#}',
            'confirmtext' => '{#i18n:attributes_matching_reset_matching_message#}',
        ),
        'attributematching' => array(
            'matching' => array(
                'titlesrc' => 'Shop-Wert',
                'titledst' => 'eBay-Wert',
            ),
        ),
    ),
), false);

MLI18n::gi()->ebay_prepareform_max_length_part1 = 'Max length of';
MLI18n::gi()->ebay_prepareform_max_length_part2 = 'attribute is';
MLI18n::gi()->ebay_prepareform_category = 'Category attribute is mandatory.';
MLI18n::gi()->ebay_prepareform_title = 'Bitte geben Sie einen Titel an.';
MLI18n::gi()->ebay_prepareform_description = 'Bitte geben Sie eine Artikelbeschreibung an.';
MLI18n::gi()->ebay_prepareform_category_attribute = ' (Kategorie Attribute) ist erforderlich und kann nicht leer sein.';
MLI18n::gi()->ebay_category_no_attributes = 'Es sind keine Attribute f&uuml;r diese Kategorie vorhanden.';
MLI18n::gi()->ebay_prepare_variations_title = '{#i18n:attributes_matching_tab_title#}';
MLI18n::gi()->ebay_prepare_variations_groups = 'eBay Groups';
MLI18n::gi()->ebay_prepare_variations_groups_custom = 'Eigene Gruppen';
MLI18n::gi()->ebay_prepare_variations_groups_new = 'Eigene Gruppe anlegen';
MLI18n::gi()->ebay_prepare_match_variations_no_selection = 'Bitte w&auml;hlen Sie eine Variantengruppe aus.';
MLI18n::gi()->ebay_prepare_match_variations_custom_ident_missing = 'Bitte w&auml;hlen Sie Bezeichner.';
MLI18n::gi()->ebay_prepare_match_variations_attribute_missing = 'Bitte w&auml;hlen Sie Attributsnamen.';
MLI18n::gi()->ebay_prepare_match_variations_not_all_matched = 'Bitte weisen Sie allen eBay Attributen ein Shop-Attribut zu.';
MLI18n::gi()->ebay_prepare_match_notice_not_all_auto_matched = 'Es konnten nicht alle ausgewählten Werte gematcht werden. Nicht-gematchte Werte werden weiterhin in den DropDown-Feldern angezeigt. Bereits gematchte Werte werden in der Produktvorbereitung berücksichtigt.';
MLI18n::gi()->ebay_prepare_match_variations_saved = 'Erfolgreich gespeichert.';
MLI18n::gi()->ebay_prepare_variations_saved = 'Es wurden alle ausgewählten Werte erfolgreich gematcht. Sie können nun Produkte mit den gematchten Attributen vorbereiten, oder mit dem Matching hier fortfahren.';
MLI18n::gi()->ebay_prepare_match_variations_delete = 'Wollen Sie die eigene Gruppe wirklich l&ouml;schen? Alle zugeh&ouml;rigen Variantenmatchings werden dann ebenfalls gel&ouml;scht.';
MLI18n::gi()->ebay_error_checkin_variation_config_empty = 'Variationen sind nicht konfiguriert.';
MLI18n::gi()->ebay_error_checkin_variation_config_cannot_calc_variations = 'Es konnten keine Variationen errechnet werden.';
MLI18n::gi()->ebay_error_checkin_variation_config_missing_nameid = 'Es konnte keine Zuordnung f&uuml;r das Shop Attribut "{#Attribute#}" bei der gew&auml;hlten Ayn24 Variantengruppe "{#MpIdentifier#}" f&uuml;r den Varianten Artikel mit der SKU "{#SKU#}" gefunden werden.';
MLI18n::gi()->ebay_prepare_variations_free_text = '{#i18n:attributes_matching_option_free_text#}';
MLI18n::gi()->ebay_prepare_variations_additional_category = '{#i18n:attributes_matching_additional_category#}';
MLI18n::gi()->ebay_prepare_variations_error_text = '{#i18n:attributes_matching_attribute_required_error#}';
MLI18n::gi()->ebay_prepare_variations_error_empty_custom_attribute_name = '{#i18n:form_action_default_empty_custom_attribute_name#}';
MLI18n::gi()->ebay_prepare_variations_error_maximal_number_custom_attributes_exceeded = '{#i18n:form_action_default_maximal_number_custom_attributes_exceeded#}';
MLI18n::gi()->ebay_prepare_variations_theme_mandatory_error = 'Bitte wählen Sie das Varianten-Design.';
MLI18n::gi()->ebay_prepare_variations_error_missing_value = '{#i18n:attributes_matching_attribute_required_missing_value#}';
MLI18n::gi()->ebay_prepare_variations_error_free_text = '{#i18n:attributes_matching_attribute_free_text_error#}';
MLI18n::gi()->ebay_prepare_variations_matching_table = '{#i18n:attributes_matching_table_matched_headline#}';
MLI18n::gi()->ebay_prepare_variations_manualy_matched = '{#i18n:attributes_matching_type_manually_matched#}';
MLI18n::gi()->ebay_prepare_variations_auto_matched = '{#i18n:attributes_matching_type_auto_matched#}';
MLI18n::gi()->ebay_prepare_variations_free_text_add = '{#i18n:attributes_matching_type_free_text#}';
MLI18n::gi()->ebay_prepare_variations_reset_info = '{#i18n:attributes_matching_reset_matching_message#}';
MLI18n::gi()->ebay_prepare_variations_change_attribute_info = '{#i18n:attributes_matching_change_attribute_info#}';
MLI18n::gi()->ebay_prepare_variations_additional_attribute_label = '{#i18n:attributes_matching_custom_attributes#}';
MLI18n::gi()->ebay_prepare_variations_separator_line_label = '{#i18n:attributes_matching_option_separator#}';
MLI18n::gi()->ebay_prepare_variations_mandatory_fields_info = '{#i18n:attributes_matching_mandatory_fields_info#}';
MLI18n::gi()->ebay_prepare_variations_already_matched = '{#i18n:attributes_matching_already_matched#}';
MLI18n::gi()->ebay_prepare_variations_category_without_attributes_info = '{#i18n:attributes_matching_category_without_attributes_message#}';
MLI18n::gi()->ebay_prepare_variations_choose_mp_value = '{#i18n:attributes_matching_option_marketplace_value#}';
MLI18n::gi()->ebay_prepare_variations_notice = '{#i18n:attributes_matching_prepared_different_notice#}';
MLI18n::gi()->ebay_varmatch_attribute_changed_on_mp = '{#i18n:attributes_matching_attribute_value_changed_from_marketplace_message#}';
MLI18n::gi()->ebay_varmatch_attribute_different_on_product = '{#i18n:attributes_matching_attribute_matched_different_global_message#}';
MLI18n::gi()->ebay_varmatch_attribute_deleted_from_mp = '{#i18n:attributes_matching_attribute_deleted_from_marketplace_message#}';
MLI18n::gi()->ebay_varmatch_attribute_value_deleted_from_mp = '{#i18n:attributes_matching_attribute_value_deleted_from_marketplace_message#}';
MLI18n::gi()->ebay_varmatch_attribute_deleted_from_shop = '{#i18n:attributes_matching_attribute_deleted_from_shop_message#}';

MLI18n::gi()->ebay_varmatch_define_name = 'Bitte geben Sie einen Bezeichner ein.';
MLI18n::gi()->ebay_varmatch_ajax_error = 'Ein Fehler ist aufgetreten.';
MLI18n::gi()->ebay_varmatch_all_select = '{#i18n:attributes_matching_option_all#}';
MLI18n::gi()->ebay_varmatch_please_select = '{#i18n:attributes_matching_option_please_select#}';
MLI18n::gi()->ebay_varmatch_auto_matchen = '{#i18n:attributes_matching_option_auto_match#}';
MLI18n::gi()->ebay_varmatch_reset_matching = '{#i18n:attributes_matching_option_reset_matching#}';
MLI18n::gi()->ebay_varmatch_delete_custom_title = 'Varianten-Matching-Gruppe l&ouml;schen';
MLI18n::gi()->ebay_varmatch_delete_custom_content = 'Wollen Sie die eigene Gruppe wirklich l&ouml;schen?<br />Alle zugeh&ouml;rigen Variantenmatchings werden dann ebenfalls gel&ouml;scht.';

MLI18n::gi()->ebay_prepare_variations_multiselect_hint = '{#i18n:attributes_matching_multi_select_hint#}';
