<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'tradoria_prepare_form__legend__details'} = 'Fiche Produit';
MLI18n::gi()->{'tradoria_prepare_form__legend__categories'} = 'Catégories Rakuten';
MLI18n::gi()->{'tradoria_prepare_form__field__categories__label'} = 'Catégories Rakuten';
MLI18n::gi()->{'tradoria_prepare_form__field__categories__hint'} = '';
MLI18n::gi()->{'tradoria_prepare_form__field__primarycategory__label'} = '1. Catégorie de la place de marché';
MLI18n::gi()->{'tradoria_prepare_form__field__primarycategory__hint'} = '';
MLI18n::gi()->{'tradoria_prepare_variations_title'} = '{#i18n:attributes_matching_tab_title#}';

