<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'check24_prepare_form__legend__details'} = 'product details';
MLI18n::gi()->{'check24_prepare_form__legend__categories'} = 'Check24 categories';
MLI18n::gi()->{'check24_prepare_form__field__shippingtime__label'} = 'Shipping time';
MLI18n::gi()->{'check24_prepare_form__field__shippingtime__hint'} = '';
MLI18n::gi()->{'check24_prepare_form__field__shippingcost__label'} = 'Shipping cost';
MLI18n::gi()->{'check24_prepare_form__field__shippingcost__hint'} = '';
