<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameHitmeister'} = 'Hitmeister';
MLI18n::gi()->{'hitmeister_label_title'} = 'Hitmeister Title';
MLI18n::gi()->{'hitmeister_category'} = 'Hitmeister Category';
MLI18n::gi()->{'hitmeister_label_item_id'} = 'Item ID';
MLI18n::gi()->{'hitmeister_search_by_title'} = 'Search by title';
MLI18n::gi()->{'hitmeister_search_by_ean'} = 'Search by ean';
MLI18n::gi()->{'hitmeister_label_not_matched'} = 'dont match';
MLI18n::gi()->{'hitmeister_upload_explanation'} = 'Uploaded articles which has an EAN known by real.de will usually be listed within an hour on real.de.
<br /><br />
EAN-articles that are not already listet on real.de will be transferred every night starting midnight by magnalister.
<br /><br />
Data will be checked and processed manually by real.de for quality control reasons. The processing can take up to 2 to 4 working days. You can check the status in your real.de administration.';
