<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'hitmeister_inventory_listing_quantity'} = 'Quantity<br />Shop / Hitmeister';
MLI18n::gi()->{'hitmeister_inventory_listing_status'} = 'Status';
MLI18n::gi()->{'hitmeister_inventory_listing_status_active'} = 'Active';
MLI18n::gi()->{'hitmeister_inventory_listing_status_pending_new'} = 'Article will be listed';
MLI18n::gi()->{'hitmeister_inventory_listing_status_pending_update'} = 'Article will be updated';
