<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameCdiscount'} = 'Cdiscount';
MLI18n::gi()->{'cdiscount_label_title'} = 'Titre Cdiscount';
MLI18n::gi()->{'cdiscount_category'} = 'Catégorie Cdiscount';
MLI18n::gi()->{'cdiscount_label_item_id'} = 'Identifiant d\'article';
MLI18n::gi()->{'cdiscount_search_by_title'} = 'Rechercher par titre';
MLI18n::gi()->{'cdiscount_search_by_ean'} = 'Rechercher par code EAN';
MLI18n::gi()->{'cdiscount_label_not_matched'} = 'ne pas classer';
MLI18n::gi()->{'cdiscount_upload_explanation'} = 'En règle générale, les produits téléchargés sont placés sur Cdiscount en quelques heures.
Si le produit n\'est pas déjà disponible sur Cdiscount, cela peut prendre jusqu\'à 24 heures.
Vous trouverez ensuite les articles sur votre compte revendeur Cdiscount.';
