<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'form_type_optional_select__true'} = 'Apply';
MLI18n::gi()->{'form_type_optional_select__false'} = 'Don\'t apply';
MLI18n::gi()->{'form_type_matching_multi_select'} = 'Multiselect';
MLI18n::gi()->{'form_type_matching_select_optional'} = 'Please choose';
MLI18n::gi()->{'form_type_matching_multi_select'} = 'Multiselect';
MLI18n::gi()->{'form_type_matching_select_all'} = 'All';
MLI18n::gi()->{'form_type_matching_select_reset'} = 'Undo matching';
MLI18n::gi()->{'form_type_matching_select_manual'} = 'Specify own values';
MLI18n::gi()->{'form_type_matching_select_auto'} = 'Auto-match';
MLI18n::gi()->{'form_type_duplicate_radiogroup'} = 'Default';
MLI18n::gi()->{'form_type_matching_optional'} = 'Do not transfer';
MLI18n::gi()->{'form_text_addon_error'} = 'The Addon {#Sku#} could not be booked.<br /><br />Error: {#Error#}';
MLI18n::gi()->{'form_text_addon_success'} = 'The Addon {#Sku#} has been booked. You will receive a confirmation E-Mail.';
MLI18n::gi()->{'form_action_default_legend'} = 'Actions';
MLI18n::gi()->{'form_action_default_empty_custom_attribute_name'} = 'Name of custom attribute cannot be empty. Please choose the attribute name.';
MLI18n::gi()->{'form_action_default_duplicated_custom_attribute_name'} = 'Custom attribute {#attributeName#} can not be the same as any predefined {#marketplace#} attribute or other custom attribute. Please choose different name.';
MLI18n::gi()->{'form_action_default_maximal_number_custom_attributes_exceeded'} = 'Maximal number of additional attributes is {#numberOfAttributes#}. Please choose {#numberOfAttributes#} additional attributes.';
MLI18n::gi()->{'form_action_prepare'} = 'Save';
MLI18n::gi()->{'form_action_unprepare'} = 'Cancel prepare';
MLI18n::gi()->{'form_action_save'} = 'Save';
MLI18n::gi()->{'form_action_wizard_save'} = 'Continue with "%s"';
MLI18n::gi()->{'form_action_finish_wizard_save'} = 'Finish and save';
MLI18n::gi()->{'form_action_expert'} = 'Expert settings';
MLI18n::gi()->{'form_action_reset'} = 'Reset';
MLI18n::gi()->{'form_text_choose'} = 'Choose';
