<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'idealo_config_account_title'} = 'Données d\'accès';
MLI18n::gi()->{'idealo_config_account_prepare'} = 'Préparation d\'articles';
MLI18n::gi()->{'idealo_config_account_price'} = 'Calcul du prix';
MLI18n::gi()->{'idealo_config_account_sync'} = 'Synchronisation';
MLI18n::gi()->{'idealo_config_account_orderimport'} = 'Importation de commandes';
MLI18n::gi()->{'idealo_config_account_emailtemplate'} = '{#i18n:configform_emailtemplate_legend#}';
MLI18n::gi()->{'idealo_config_message_no_csv_table_yet'} = 'Si vous n\'avez pas encore de table CSV. Créez d\'abord un article et vous trouverez ensuite, ici, le chemin d\'accés du fichier CSV. ';
MLI18n::gi()->{'idealo_methods_not_available'} = 'Entrez et enregistrez le Direktkauf-Token sous "Données d\'accès"';
MLI18n::gi()->{'idealo_configform_orderimport_payment_values__textfield__title'} = 'De la zone de texte';
MLI18n::gi()->{'idealo_configform_orderimport_payment_values__textfield__textoption'} = '1';
MLI18n::gi()->{'idealo_configform_orderimport_payment_values__matching__title'} = 'Classement automatique';
