<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'ML_COMPARISON_SHOPPING_TEXT_NO_CSV_TABLE_YET'} = 'ML_COMPARISON_SHOPPING_TEXT_NO_CSV_TABLE_YET';
MLI18n::gi()->{'sModuleNameIdealo'} = 'idealo';
