<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Idealo_Productlist_Cell_aPreparedStatus__OK__title'} = 'Préparé avec succès';
MLI18n::gi()->{'Idealo_Productlist_Cell_aPreparedStatus__ERROR__title'} = 'Erreur dans la préparation';
MLI18n::gi()->{'Idealo_Productlist_Cell_aPreparedStatus__OPEN__title'} = 'Préparation non vérifié';
MLI18n::gi()->{'Idealo_Productlist_Filter_aPreparedStatus__OK'} = 'Préparé avec succès';
MLI18n::gi()->{'Idealo_Productlist_Filter_aPreparedStatus__ERROR'} = 'Erreur dans la préparation';
MLI18n::gi()->{'Idealo_Productlist_Filter_aPreparedStatus__OPEN'} = 'Préparation non vérifié';
MLI18n::gi()->{'Idealo_Productlist_Cell_aPreparedType__Chinese'} = 'Enchères(Chine)';
MLI18n::gi()->{'Idealo_Productlist_Cell_aPreparedType__FixedPriceItem'} = 'Prix fixe';
MLI18n::gi()->{'Idealo_Productlist_Cell_aPreparedType__StoresFixedPrice'} = 'Prix fixe (boutique DaWanda)';
MLI18n::gi()->{'Idealo_Productlist_Header_sPreparedType'} = 'Type d\'enchère';
MLI18n::gi()->{'ML_IDEALO_TEXT_NO_MATCHED_PRODUCTS'} = 'Aucun produit n\'a été préparé pour idéalo. Avant de pouvoir télécharger vos produits, vous devez les éditer sous l\'onglet "péparer les articles".<br>
Si certains articles déjà préparés n\'apparaissent pas, vérifiez s\'ils ne sont pas définies comme inactif par la configuration que vous auriez défini sous idealo -> "Configuration" -> "Préparation d\'articles" rubrique "Statut du filtre".';
