<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'etsy_config_account_title'} = 'Zugangsdaten';
MLI18n::gi()->{'etsy_config_account_prepare'} = 'Artikelvorbereitung';
MLI18n::gi()->{'etsy_config_account_price'} = 'Preisberechnung';
MLI18n::gi()->{'etsy_config_account_sync'} = 'Synchronisation';
MLI18n::gi()->{'etsy_config_account_orderimport'} = 'Bestellimport';
