<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameEtsy'} = 'Etsy';
MLI18n::gi()->{'etsy_upload_explanation'} = 'Der Marktplatz verarbeitet Ihre Daten und prüft sie auf inhaltliche Fehler. Die Artikelbearbeitung kann bis zu 24 Stunden dauern.';
MLI18n::gi()->{'etsy_info_add_upload'} = 'Jeder Artikel, der auf dem Etsy Marktplatz<br/> eingestellt wurde, wird von Etsy berechnet! <br/><br/> Bitte warten Sie einen Moment....';
MLI18n::gi()->{'etsy_prepare_description_not_valid'} = 'Die Artikelbeschreibung ist zu lang. Die maximale Anzahl der Zeichen beträgt 63000.';
MLI18n::gi()->{'etsy_prepare_images_not_valid'} = 'Das Bild ist zu groß. Die maximal zulässige Bildgröße beträgt 3000 x 3000 px.';
MLI18n::gi()->{'etsy_prepare_images_not_exist'} = 'Es muss mindestens ein Bild für den Artikel vorhanden sein!';
MLI18n::gi()->{'etsy_prepare_description_not_exist'} = 'Die Artikelbeschreibung ist zu kurz.';
MLI18n::gi()->{'etsy_prepare_price_not_valid'} = 'Minimaler Artikelpreis auf Etsy ist 0.17£.';
MLI18n::gi()->{'etsy_prepare_quantity_not_valid'} = 'Der Bestand für ein Produkt darf nicht größe als 999 sein.';

MLI18n::gi()->{'etsy_inventory_listing_status_new'} = 'Produkt wird erstellt';
MLI18n::gi()->{'etsy_inventory_listing_status_update'} = 'Produkt wird aktualisiert';
MLI18n::gi()->{'etsy_inventory_listing_status_active'} = 'Aktiv';