<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'amazon_config_orderimport__field__orderimport.shippingmethod__label'} = 'amazon_config_orderimport__field__orderimport.shippingmethod__label';
MLI18n::gi()->{'amazon_config_orderimport__field__orderimport.shippingmethod__help'} = 'amazon_config_orderimport__field__orderimport.shippingmethod__help';
MLI18n::gi()->{'amazon_config_orderimport__field__orderimport.shippingmethod__hint'} = '';
MLI18n::gi()->{'amazon_config_orderimport__field__orderimport.fbashippingmethod__label'} = 'amazon_config_orderimport__field__orderimport.fbashippingmethod__label';
MLI18n::gi()->{'amazon_config_orderimport__field__orderimport.fbashippingmethod__help'} = 'amazon_config_orderimport__field__orderimport.fbashippingmethod__help';
MLI18n::gi()->{'amazon_config_orderimport__field__orderimport.fbashippingmethod__hint'} = '';
