<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Orderimport_CurrencyCodeDontExistsError'} = 'La commande {#mpOrderId#} ne pourra pas être importée, si vous n\'avez pas configuré, dans votre boutique, la devise {#ISO#} standart pour la place de marché, dont elle émane.';
