<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameRicardo'} = 'Ricardo';
MLI18n::gi()->{'ricardo_inventory_listing_lastSyncTime'} = 'Dernière synchronisation';
MLI18n::gi()->{'ricardo_inventory_listing_itemId'} = 'Référence';
MLI18n::gi()->{'ricardo_inventory_listing_marketplaceTitle'} = 'Nom sur Ricardo';
MLI18n::gi()->{'ricardo_inventory_listing_auction_has_bids'} = 'Enchères sur l\'objet!';
MLI18n::gi()->{'ricardo_inventory_listing_auction_has_bids_tooltip'} = 'À partir du moment où un enchérisseur fait une offre, l\'enchère ne peut être clôturée!';
MLI18n::gi()->{'ricardo_inventory_listing_status'} = 'Statut';
MLI18n::gi()->{'ricardo_inventory_listing_bid_count'} = 'Compteur d\'enchères';
MLI18n::gi()->{'ricardo_productlist_upload_shippingfee_notice_content'} = 'Veuillez noter que ricardo.ch fixe en principe une limite de 100 annonces publiées simultanément par vendeur. Cette limite peut être adaptée au cas par cas, à la demande du vendeur. Avant de charger votre produit, assurez-vous bien de ne dépassez pas cette limite et vérifiez le log d\'erreurs au moins 30 minutes après le chargement. 
<br><br>
Souhaitez-vous charger vos articles dès maintenant ?';