<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'sModuleNameRicardo'} = 'Ricardo';
MLI18n::gi()->{'ricardo_inventory_listing_lastSyncTime'} = 'Last synchronization';
MLI18n::gi()->{'ricardo_inventory_listing_itemId'} = 'Article number';
MLI18n::gi()->{'ricardo_inventory_listing_marketplaceTitle'} = 'Ricardo Title';
MLI18n::gi()->{'ricardo_inventory_listing_auction_has_bids'} = 'Auction with bids!';
MLI18n::gi()->{'ricardo_inventory_listing_auction_has_bids_tooltip'} = 'Auctions with bids are not allowed to be ended!';
MLI18n::gi()->{'ricardo_inventory_listing_status'} = 'Status';
MLI18n::gi()->{'ricardo_inventory_listing_bid_count'} = 'Bid count';
MLI18n::gi()->{'ricardo_productlist_upload_shippingfee_notice_content'} = 'Please note that ricardo.ch has generally limited every merchant to 100 simultaneous offers, however, ricardo.ch can customize this limit individually for every merchant. Prior to uploading, please check whether your products are exceeding this limit. At the earliest, you can check your error log 30 minutes after uploading.<br><br>Do you want to upload your products now?';