<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Hood_CheckinForm__Price'} = 'Hood_CheckinForm__Price';
MLI18n::gi()->{'Hood_CheckinForm__Amount'} = 'Hood_CheckinForm__Amount';
MLI18n::gi()->{'Hood_CheckinForm__ShippingTime'} = 'Hood_CheckinForm__ShippingTime';
MLI18n::gi()->{'Hood_CheckinForm__ShopPrice'} = 'Hood_CheckinForm__ShopPrice';
MLI18n::gi()->{'Hood_CheckinForm__SuggestedPrice'} = 'Hood_CheckinForm__SuggestedPrice';
MLI18n::gi()->{'Hood_CheckinForm__HitPrice'} = 'Hood_CheckinForm__HitPrice';
MLI18n::gi()->{'Hood_CheckinForm__AvailibleAmount'} = 'Hood_CheckinForm__AvailibleAmount';
MLI18n::gi()->{'Hood_CheckinForm__SuggestedAmount'} = 'Hood_CheckinForm__SuggestedAmount';
