<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Hood_Productlist_Cell_aPreparedStatus__OK__title'} = 'Hood_Productlist_Cell_aPreparedStatus__OK__title';
MLI18n::gi()->{'Hood_Productlist_Cell_aPreparedStatus__ERROR__title'} = 'Hood_Productlist_Cell_aPreparedStatus__ERROR__title';
MLI18n::gi()->{'Hood_Productlist_Cell_aPreparedStatus__OPEN__title'} = 'Hood_Productlist_Cell_aPreparedStatus__OPEN__title';
MLI18n::gi()->{'Hood_Productlist_Filter_aPreparedStatus__OK'} = 'Hood_Productlist_Filter_aPreparedStatus__OK';
MLI18n::gi()->{'Hood_Productlist_Filter_aPreparedStatus__ERROR'} = 'Hood_Productlist_Filter_aPreparedStatus__ERROR';
MLI18n::gi()->{'Hood_Productlist_Cell_aPreparedType__Chinese'} = 'Hood_Productlist_Cell_aPreparedType__Chinese';
MLI18n::gi()->{'Hood_Productlist_Cell_aPreparedType__FixedPriceItem'} = 'Hood_Productlist_Cell_aPreparedType__FixedPriceItem';
MLI18n::gi()->{'Hood_Productlist_Cell_aPreparedType__StoresFixedPrice'} = 'Hood_Productlist_Cell_aPreparedType__StoresFixedPrice';
MLI18n::gi()->{'Hood_Productlist_Header_sPreparedType'} = 'Hood_Productlist_Header_sPreparedType';
MLI18n::gi()->{'Hood_Productlist_Prepare_sResetValuesButton'} = 'Hood_Productlist_Prepare_sResetValuesButton';
MLI18n::gi()->{'Hood_Productlist_Prepare_aResetValues__buttons__ok'} = 'Hood_Productlist_Prepare_aResetValues__buttons__ok';
MLI18n::gi()->{'Hood_Productlist_Prepare_aResetValues__buttons__abort'} = 'Hood_Productlist_Prepare_aResetValues__buttons__abort';
MLI18n::gi()->{'Hood_Productlist_Prepare_aResetValues__checkboxes__title'} = 'Hood_Productlist_Prepare_aResetValues__checkboxes__title';
MLI18n::gi()->{'Hood_Productlist_Prepare_aResetValues__checkboxes__subtitle'} = 'Hood_Productlist_Prepare_aResetValues__checkboxes__subtitle';
MLI18n::gi()->{'Hood_Productlist_Prepare_aResetValues__checkboxes__description'} = 'Hood_Productlist_Prepare_aResetValues__checkboxes__description';
MLI18n::gi()->{'Hood_Productlist_Prepare_aResetValues__checkboxes__pictures'} = 'Hood_Productlist_Prepare_aResetValues__checkboxes__pictures';
MLI18n::gi()->{'Hood_Productlist_Prepare_aResetValues__checkboxes__unprepare'} = 'Hood_Productlist_Prepare_aResetValues__checkboxes__unprepare';