<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'idealo_config_account_title'} = 'Login details';
MLI18n::gi()->{'idealo_config_account_prepare'} = 'Item Preparation';
MLI18n::gi()->{'idealo_config_account_price'} = 'Price Calculation';
MLI18n::gi()->{'idealo_config_account_sync'} = 'Synchronization';
MLI18n::gi()->{'idealo_config_account_orderimport'} = 'Order Import';
MLI18n::gi()->{'idealo_config_account_emailtemplate'} = '{#i18n:configform_emailtemplate_legend#}';
MLI18n::gi()->{'idealo_config_message_no_csv_table_yet'} = 'No CSV sheet created yet: Please trigger an article first. You will find the CSV-path after that here.';
MLI18n::gi()->{'idealo_methods_not_available'} = 'Please add and save the direct-buy-token in "Login Data" first.';
MLI18n::gi()->{'idealo_configform_orderimport_payment_values__textfield__title'} = 'From textfield';
MLI18n::gi()->{'idealo_configform_orderimport_payment_values__textfield__textoption'} = '1';
MLI18n::gi()->{'idealo_configform_orderimport_payment_values__matching__title'} = 'Automatic allocation';