<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'ML_COMPARISON_SHOPPING_TEXT_NO_CSV_TABLE_YET'} = 'No CSV sheet created yet: Please trigger an article first. You will find the CSV-path after that here.';
MLI18n::gi()->{'sModuleNameIdealo'} = 'Idealo';
