<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'Idealo_Productlist_Cell_aPreparedStatus__OK__title'} = 'Successfully prepared';
MLI18n::gi()->{'Idealo_Productlist_Cell_aPreparedStatus__ERROR__title'} = 'Faultly prepared';
MLI18n::gi()->{'Idealo_Productlist_Cell_aPreparedStatus__OPEN__title'} = 'Prepared not checked';
MLI18n::gi()->{'Idealo_Productlist_Filter_aPreparedStatus__OK'} = 'Successfully prepared';
MLI18n::gi()->{'Idealo_Productlist_Filter_aPreparedStatus__ERROR'} = 'Faultly prepared';
MLI18n::gi()->{'Idealo_Productlist_Filter_aPreparedStatus__OPEN'} = 'Prepared not checked';
MLI18n::gi()->{'Idealo_Productlist_Cell_aPreparedType__Chinese'} = 'Auction (Chinese)';
MLI18n::gi()->{'Idealo_Productlist_Cell_aPreparedType__FixedPriceItem'} = 'Fix price';
MLI18n::gi()->{'Idealo_Productlist_Cell_aPreparedType__StoresFixedPrice'} = 'Fix price (DaWanda Store)';
MLI18n::gi()->{'Idealo_Productlist_Header_sPreparedType'} = 'Auction type';
MLI18n::gi()->{'ML_IDEALO_TEXT_NO_MATCHED_PRODUCTS'} = 'No items have been prepared for idealo yet. You can prepare items by selecting the "Product Prepare" tab.<br>
If you miss some products you already have prepared, please check whether the products have active status, and if not, whether the configuration allows to upload inactive iems.';
