<?php
/* Autogenerated file. Do not change! */

MLI18n::gi()->{'etsy_config_account_title'} = 'Login details';
MLI18n::gi()->{'etsy_config_account_prepare'} = 'Item preparation';
MLI18n::gi()->{'etsy_config_account_price'} = 'Price calculation';
MLI18n::gi()->{'etsy_config_account_sync'} = 'Synchronization';
MLI18n::gi()->{'etsy_config_account_orderimport'} = 'Order import';
